# Generated by Django 3.2.12 on 2022-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='core.CategoryModel'),
        ),
    ]
